/********************************************************************
* MidUnpackDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MidUnpackDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMidUnpackDictionary();
extern void G__cpp_setup_inheritanceMidUnpackDictionary();
extern void G__cpp_setup_typetableMidUnpackDictionary();
extern void G__cpp_setup_memvarMidUnpackDictionary();
extern void G__cpp_setup_globalMidUnpackDictionary();
extern void G__cpp_setup_memfuncMidUnpackDictionary();
extern void G__cpp_setup_funcMidUnpackDictionary();
extern void G__set_cpp_environmentMidUnpackDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGriffinFragment.hh"
#include "TFragmentQueue.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MidUnpackDictionaryLN_TClass;
extern G__linked_taginfo G__MidUnpackDictionaryLN_TBuffer;
extern G__linked_taginfo G__MidUnpackDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__MidUnpackDictionaryLN_TObject;
extern G__linked_taginfo G__MidUnpackDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__MidUnpackDictionaryLN_string;
extern G__linked_taginfo G__MidUnpackDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MidUnpackDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MidUnpackDictionaryLN_TObjArray;
extern G__linked_taginfo G__MidUnpackDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MidUnpackDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MidUnpackDictionaryLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__MidUnpackDictionaryLN_TGriffinFragment;
extern G__linked_taginfo G__MidUnpackDictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MidUnpackDictionaryLN_TStopwatch;
extern G__linked_taginfo G__MidUnpackDictionaryLN_TFragmentQueue;
extern G__linked_taginfo G__MidUnpackDictionaryLN_MultitonlETFragmentQueuecOstringgR;
extern G__linked_taginfo G__MidUnpackDictionaryLN_maplEstringcOTFragmentQueuemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTFragmentQueuemUgRsPgRsPgR;
extern G__linked_taginfo G__MidUnpackDictionaryLN_dequelETGriffinFragmentmUcOallocatorlETGriffinFragmentmUgRsPgR;
extern G__linked_taginfo G__MidUnpackDictionaryLN_queuelETGriffinFragmentmUcOdequelETGriffinFragmentmUcOallocatorlETGriffinFragmentmUgRsPgRsPgR;

/* STUB derived class for protected member access */
