//
// File generated by rootcint at Wed Jun 25 13:49:24 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME TMidasEventDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TMidasEventDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TMidasEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TMidasEvent(void *p = 0);
   static void *newArray_TMidasEvent(Long_t size, void *p);
   static void delete_TMidasEvent(void *p);
   static void deleteArray_TMidasEvent(void *p);
   static void destruct_TMidasEvent(void *p);
   static void streamer_TMidasEvent(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TMidasEvent*)
   {
      ::TMidasEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TMidasEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TMidasEvent", ::TMidasEvent::Class_Version(), "./../include/TMidasEvent.h", 32,
                  typeid(::TMidasEvent), DefineBehavior(ptr, ptr),
                  &::TMidasEvent::Dictionary, isa_proxy, 0,
                  sizeof(::TMidasEvent) );
      instance.SetNew(&new_TMidasEvent);
      instance.SetNewArray(&newArray_TMidasEvent);
      instance.SetDelete(&delete_TMidasEvent);
      instance.SetDeleteArray(&deleteArray_TMidasEvent);
      instance.SetDestructor(&destruct_TMidasEvent);
      instance.SetStreamerFunc(&streamer_TMidasEvent);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TMidasEvent*)
   {
      return GenerateInitInstanceLocal((::TMidasEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TMidasEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TMidasEvent::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TMidasEvent::Class_Name()
{
   return "TMidasEvent";
}

//______________________________________________________________________________
const char *TMidasEvent::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TMidasEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TMidasEvent::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TMidasEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TMidasEvent::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TMidasEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TMidasEvent::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TMidasEvent*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TMidasEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class TMidasEvent.

   TObject::Streamer(R__b);
}

//______________________________________________________________________________
void TMidasEvent::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TMidasEvent.
      TClass *R__cl = ::TMidasEvent::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fEventHeader", (void*)&fEventHeader);
      R__insp.InspectMember("TMidas_EVENT_HEADER", (void*)&fEventHeader, "fEventHeader.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fData", &fData);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fBanksN", &fBanksN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fBankList", &fBankList);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fAllocatedByUs", &fAllocatedByUs);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TMidasEvent(void *p) {
      return  p ? new(p) ::TMidasEvent : new ::TMidasEvent;
   }
   static void *newArray_TMidasEvent(Long_t nElements, void *p) {
      return p ? new(p) ::TMidasEvent[nElements] : new ::TMidasEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_TMidasEvent(void *p) {
      delete ((::TMidasEvent*)p);
   }
   static void deleteArray_TMidasEvent(void *p) {
      delete [] ((::TMidasEvent*)p);
   }
   static void destruct_TMidasEvent(void *p) {
      typedef ::TMidasEvent current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TMidasEvent(TBuffer &buf, void *obj) {
      ((::TMidasEvent*)obj)->::TMidasEvent::Streamer(buf);
   }
} // end of namespace ROOT for class ::TMidasEvent

/********************************************************
* TMidasEventDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTMidasEventDict();

extern "C" void G__set_cpp_environmentTMidasEventDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("../include/TMidasEvent.h");
  G__cpp_reset_tagtableTMidasEventDict();
}
#include <new>
extern "C" int G__cpp_dllrevTMidasEventDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TMidasEvent */
static int G__TMidasEventDict_196_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TMidasEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TMidasEvent[n];
     } else {
       p = new((void*) gvp) TMidasEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TMidasEvent;
     } else {
       p = new((void*) gvp) TMidasEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TMidasEventDictLN_TMidasEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TMidasEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TMidasEvent(*(TMidasEvent*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) TMidasEvent(*(TMidasEvent*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TMidasEventDictLN_TMidasEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TMidasEvent& obj = ((TMidasEvent*) G__getstructoffset())->operator=(*(TMidasEvent*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMidasEvent*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMidasEvent*) G__getstructoffset())->Copy(*(TMidasEvent*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TMidasEvent*) G__getstructoffset())->GetEventId());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((const TMidasEvent*) G__getstructoffset())->GetTriggerMask());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const TMidasEvent*) G__getstructoffset())->GetSerialNumber());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const TMidasEvent*) G__getstructoffset())->GetTimeStamp());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const TMidasEvent*) G__getstructoffset())->GetDataSize());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ((const TMidasEvent*) G__getstructoffset())->GetBankList());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const TMidasEvent*) G__getstructoffset())->FindBank((const char*) G__int(libp->para[0]), (int*) G__int(libp->para[1])
, (int*) G__int(libp->para[2]), (void**) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const TMidasEvent*) G__getstructoffset())->LocateBank((void*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (void**) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const TMidasEvent*) G__getstructoffset())->IsBank32());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const TMidasEvent*) G__getstructoffset())->IterateBank((TMidasEvent::TMidas_BANK**) G__int(libp->para[0]), (char**) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const TMidasEvent*) G__getstructoffset())->IterateBank32((TMidasEvent::TMidas_BANK32**) G__int(libp->para[0]), (char**) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TMidasEvent*) G__getstructoffset())->GetEventHeader());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ((TMidasEvent*) G__getstructoffset())->GetData());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMidasEvent*) G__getstructoffset())->AllocateData();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMidasEvent*) G__getstructoffset())->SetData((uint32_t) G__int(libp->para[0]), (char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TMidasEvent*) G__getstructoffset())->SetBankList());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const TMidasEvent*) G__getstructoffset())->IsGoodSize());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMidasEvent*) G__getstructoffset())->SwapBytesEventHeader();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TMidasEvent*) G__getstructoffset())->SwapBytes((bool) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TMidasEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TMidasEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TMidasEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TMidasEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMidasEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TMidasEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TMidasEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TMidasEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TMidasEventDict_196_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TMidasEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TMidasEvent G__TTMidasEvent;
static int G__TMidasEventDict_196_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TMidasEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TMidasEvent*) (soff+(sizeof(TMidasEvent)*i)))->~G__TTMidasEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TMidasEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TMidasEvent*) (soff))->~G__TTMidasEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TMidasEvent */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTMidasEventDict {
 public:
  G__Sizep2memfuncTMidasEventDict(): p(&G__Sizep2memfuncTMidasEventDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTMidasEventDict::*p)();
};

size_t G__get_sizep2memfuncTMidasEventDict()
{
  G__Sizep2memfuncTMidasEventDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTMidasEventDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TMidasEventDictLN_TMidasEvent))) {
     TMidasEvent *G__Lderived;
     G__Lderived=(TMidasEvent*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TMidasEventDictLN_TMidasEvent),G__get_linked_tagnum(&G__TMidasEventDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTMidasEventDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TMidasEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TMidasEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TMidasEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TMidasEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TMidasEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TMidasEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TMidasEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TMidasEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TMidasEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TMidasEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("uint16_t",114,-1,0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("uint32_t",104,-1,0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TMidasEvent */
static void G__setup_memvarTMidasEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TMidasEventDictLN_TMidasEvent));
   { TMidasEvent *p; p=(TMidasEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TMidasEventDictLN_TMidas_EVENT_HEADER),-1,-1,2,"fEventHeader=",0,"/< event header");
   G__memvar_setup((void*)0,67,0,0,-1,-1,-1,2,"fData=",0,"/< event data buffer");
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fBanksN=",0,"/< number of banks in this event");
   G__memvar_setup((void*)0,67,0,0,-1,-1,-1,2,"fBankList=",0,"/< list of bank names in this event");
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"fAllocatedByUs=",0,"/< \"true\" if we own the data buffer");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TMidasEventDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTMidasEventDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTMidasEvent(void) {
   /* TMidasEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TMidasEventDictLN_TMidasEvent));
   G__memfunc_setup("TMidasEvent",1092,G__TMidasEventDict_196_0_1, 105, G__get_linked_tagnum(&G__TMidasEventDictLN_TMidasEvent), -1, 0, 0, 1, 1, 0, "", "/< default constructor", (void*) NULL, 0);
   G__memfunc_setup("TMidasEvent",1092,G__TMidasEventDict_196_0_2, 105, G__get_linked_tagnum(&G__TMidasEventDictLN_TMidasEvent), -1, 0, 1, 1, 1, 0, "u 'TMidasEvent' - 11 - -", "/< copy constructor", (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__TMidasEventDict_196_0_3, 117, G__get_linked_tagnum(&G__TMidasEventDictLN_TMidasEvent), -1, 1, 1, 1, 1, 0, "u 'TMidasEvent' - 11 - -", "/< assignement operator", (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__TMidasEventDict_196_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", "/< clear event for reuse", (void*) NULL, 0);
   G__memfunc_setup("Copy",411,G__TMidasEventDict_196_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMidasEvent' - 11 - -", "/< copy helper", (void*) NULL, 0);
   G__memfunc_setup("Print",525,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 8, "C - - 10 '\"\"' option", "/< show all event information", (void*) NULL, 1);
   G__memfunc_setup("GetEventId",975,G__TMidasEventDict_196_0_7, 114, -1, G__defined_typename("uint16_t"), 0, 0, 1, 1, 8, "", "/< return the event id", (void*) NULL, 0);
   G__memfunc_setup("GetTriggerMask",1408,G__TMidasEventDict_196_0_8, 114, -1, G__defined_typename("uint16_t"), 0, 0, 1, 1, 8, "", "/< return the triger mask", (void*) NULL, 0);
   G__memfunc_setup("GetSerialNumber",1513,G__TMidasEventDict_196_0_9, 104, -1, G__defined_typename("uint32_t"), 0, 0, 1, 1, 8, "", "/< return the serial number", (void*) NULL, 0);
   G__memfunc_setup("GetTimeStamp",1204,G__TMidasEventDict_196_0_10, 104, -1, G__defined_typename("uint32_t"), 0, 0, 1, 1, 8, "", "/< return the time stamp (unix time in seconds)", (void*) NULL, 0);
   G__memfunc_setup("GetDataSize",1077,G__TMidasEventDict_196_0_11, 104, -1, G__defined_typename("uint32_t"), 0, 0, 1, 1, 8, "", "/< return the event size", (void*) NULL, 0);
   G__memfunc_setup("GetBankList",1080,G__TMidasEventDict_196_0_12, 67, -1, -1, 0, 0, 1, 1, 9, "", "/< return a list of data banks", (void*) NULL, 0);
   G__memfunc_setup("FindBank",765,G__TMidasEventDict_196_0_13, 105, -1, -1, 0, 4, 1, 1, 8, 
"C - - 10 - bankName I - - 0 - bankLength "
"I - - 0 - bankType Y - - 2 - bankPtr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LocateBank",980,G__TMidasEventDict_196_0_14, 105, -1, -1, 0, 3, 1, 1, 8, 
"Y - - 10 - unused C - - 10 - bankName "
"Y - - 2 - bankPtr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsBank32",669,G__TMidasEventDict_196_0_15, 103, -1, -1, 0, 0, 1, 1, 8, "", "/< returns \"true\" if event uses 32-bit banks", (void*) NULL, 0);
   G__memfunc_setup("IterateBank",1098,G__TMidasEventDict_196_0_16, 105, -1, -1, 0, 2, 1, 1, 8, 
"U 'TMidasEvent::TMidas_BANK' - 2 - - C - - 2 - pdata", "/< iterate through 16-bit data banks", (void*) NULL, 0);
   G__memfunc_setup("IterateBank32",1199,G__TMidasEventDict_196_0_17, 105, -1, -1, 0, 2, 1, 1, 8, 
"U 'TMidasEvent::TMidas_BANK32' - 2 - - C - - 2 - pdata", "/< iterate through 32-bit data banks", (void*) NULL, 0);
   G__memfunc_setup("GetEventHeader",1387,G__TMidasEventDict_196_0_18, 85, G__get_linked_tagnum(&G__TMidasEventDictLN_TMidas_EVENT_HEADER), -1, 0, 0, 1, 1, 0, "", "/< return pointer to the event header", (void*) NULL, 0);
   G__memfunc_setup("GetData",666,G__TMidasEventDict_196_0_19, 67, -1, -1, 0, 0, 1, 1, 0, "", "/< return pointer to the data buffer", (void*) NULL, 0);
   G__memfunc_setup("AllocateData",1183,G__TMidasEventDict_196_0_20, 121, -1, -1, 0, 0, 1, 1, 0, "", "/< allocate data buffer using the existing event header", (void*) NULL, 0);
   G__memfunc_setup("SetData",678,G__TMidasEventDict_196_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"h - 'uint32_t' 0 - dataSize C - - 0 - dataBuffer", "/< set an externally allocated data buffer", (void*) NULL, 0);
   G__memfunc_setup("SetBankList",1092,G__TMidasEventDict_196_0_22, 105, -1, -1, 0, 0, 1, 1, 0, "", "/< create the list of data banks, return number of banks", (void*) NULL, 0);
   G__memfunc_setup("IsGoodSize",992,G__TMidasEventDict_196_0_23, 103, -1, -1, 0, 0, 1, 1, 8, "", "/< validate the event length", (void*) NULL, 0);
   G__memfunc_setup("SwapBytesEventHeader",2029,G__TMidasEventDict_196_0_24, 121, -1, -1, 0, 0, 1, 1, 0, "", "/< convert event header between little-endian (Linux-x86) and big endian (MacOS-PPC) ", (void*) NULL, 0);
   G__memfunc_setup("SwapBytes",930,G__TMidasEventDict_196_0_25, 105, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - -", "/< convert event data between little-endian (Linux-x86) and big endian (MacOS-PPC) ", (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TMidasEventDict_196_0_26, 85, G__get_linked_tagnum(&G__TMidasEventDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TMidasEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TMidasEventDict_196_0_27, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TMidasEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TMidasEventDict_196_0_28, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TMidasEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TMidasEventDict_196_0_29, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TMidasEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TMidasEventDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TMidasEventDict_196_0_33, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TMidasEventDict_196_0_34, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TMidasEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TMidasEventDict_196_0_35, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TMidasEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TMidasEventDict_196_0_36, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TMidasEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TMidasEventDict_196_0_37, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TMidasEvent::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~TMidasEvent", 1218, G__TMidasEventDict_196_0_38, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTMidasEventDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTMidasEventDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTMidasEventDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TMidasEventDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TMidasEventDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TMidasEventDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TMidasEventDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TMidasEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TMidasEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TMidasEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TMidasEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TMidasEventDictLN_TMidas_EVENT_HEADER = { "TMidas_EVENT_HEADER" , 115 , -1 };
G__linked_taginfo G__TMidasEventDictLN_TMidasEvent = { "TMidasEvent" , 99 , -1 };
G__linked_taginfo G__TMidasEventDictLN_TMidasEventcLcLTMidas_BANK = { "TMidasEvent::TMidas_BANK" , 115 , -1 };
G__linked_taginfo G__TMidasEventDictLN_TMidasEventcLcLTMidas_BANK32 = { "TMidasEvent::TMidas_BANK32" , 115 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTMidasEventDict() {
  G__TMidasEventDictLN_TClass.tagnum = -1 ;
  G__TMidasEventDictLN_TBuffer.tagnum = -1 ;
  G__TMidasEventDictLN_TMemberInspector.tagnum = -1 ;
  G__TMidasEventDictLN_TObject.tagnum = -1 ;
  G__TMidasEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TMidasEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TMidasEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TMidasEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TMidasEventDictLN_TMidas_EVENT_HEADER.tagnum = -1 ;
  G__TMidasEventDictLN_TMidasEvent.tagnum = -1 ;
  G__TMidasEventDictLN_TMidasEventcLcLTMidas_BANK.tagnum = -1 ;
  G__TMidasEventDictLN_TMidasEventcLcLTMidas_BANK32.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTMidasEventDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TMidasEventDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TMidasEventDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TMidasEventDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TMidasEventDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TMidasEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TMidasEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TMidasEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TMidasEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TMidasEventDictLN_TMidas_EVENT_HEADER);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TMidasEventDictLN_TMidasEvent),sizeof(TMidasEvent),-1,32512,(char*)NULL,G__setup_memvarTMidasEvent,G__setup_memfuncTMidasEvent);
   G__get_linked_tagnum_fwd(&G__TMidasEventDictLN_TMidasEventcLcLTMidas_BANK);
   G__get_linked_tagnum_fwd(&G__TMidasEventDictLN_TMidasEventcLcLTMidas_BANK32);
}
extern "C" void G__cpp_setupTMidasEventDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTMidasEventDict()");
  G__set_cpp_environmentTMidasEventDict();
  G__cpp_setup_tagtableTMidasEventDict();

  G__cpp_setup_inheritanceTMidasEventDict();

  G__cpp_setup_typetableTMidasEventDict();

  G__cpp_setup_memvarTMidasEventDict();

  G__cpp_setup_memfuncTMidasEventDict();
  G__cpp_setup_globalTMidasEventDict();
  G__cpp_setup_funcTMidasEventDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTMidasEventDict();
  return;
}
class G__cpp_setup_initTMidasEventDict {
  public:
    G__cpp_setup_initTMidasEventDict() { G__add_setup_func("TMidasEventDict",(G__incsetup)(&G__cpp_setupTMidasEventDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTMidasEventDict() { G__remove_setup_func("TMidasEventDict"); }
};
G__cpp_setup_initTMidasEventDict G__cpp_setup_initializerTMidasEventDict;

