/********************************************************************
* XmlOdbDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error XmlOdbDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableXmlOdbDict();
extern void G__cpp_setup_inheritanceXmlOdbDict();
extern void G__cpp_setup_typetableXmlOdbDict();
extern void G__cpp_setup_memvarXmlOdbDict();
extern void G__cpp_setup_globalXmlOdbDict();
extern void G__cpp_setup_memfuncXmlOdbDict();
extern void G__cpp_setup_funcXmlOdbDict();
extern void G__set_cpp_environmentXmlOdbDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../include/XmlOdb.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__XmlOdbDictLN_TClass;
extern G__linked_taginfo G__XmlOdbDictLN_TBuffer;
extern G__linked_taginfo G__XmlOdbDictLN_TMemberInspector;
extern G__linked_taginfo G__XmlOdbDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__XmlOdbDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__XmlOdbDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__XmlOdbDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__XmlOdbDictLN_TXMLNode;
extern G__linked_taginfo G__XmlOdbDictLN_TDOMParser;
extern G__linked_taginfo G__XmlOdbDictLN_VirtualOdb;
extern G__linked_taginfo G__XmlOdbDictLN_XmlOdb;

/* STUB derived class for protected member access */
